import { supabase } from "./supabase";
import type { Activation } from "@/types/database.types";

/** Most recent activation for the user (any status), or null. */
export async function getLatestActivation(email: string): Promise<Activation | null> {
  const { data } = await supabase
    .from("activations")
    .select("*")
    .eq("email", email)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  return data ?? null;
}

/**
 * Guarantees the user has an activation token to bind a device.
 * Reuses an existing pending (unbound) activation if present, otherwise creates one.
 * The token is generated by the DB default; the HWID is set later by the DesktopApp.
 */
export async function ensureActivation(email: string, appVersion?: string): Promise<Activation | null> {
  const { data: pending } = await supabase
    .from("activations")
    .select("*")
    .eq("email", email)
    .is("hwid", null)
    .eq("status", "pending")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (pending) return pending;

  const { data, error } = await supabase
    .from("activations")
    .insert({ email, app_version: appVersion ?? null })
    .select()
    .single();
  if (error) return null;
  return data;
}
